database: h2

spring:
  profiles.include: oauth

  config:
    import: aws.yml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  sql:
    init:
      schema-locations: classpath*:db/${database}/schema.sql
      data-locations: classpath*:db/${database}/data.sql
#      mode: always  # 모든 DB에 적용

logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace

    com.amazonaws:
      util:
        EC2MetadataUtils: error
